name: Staging squirrel deploy

on:
  push:
    branches: [main]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
  deploy_desktop:
    runs-on: windows-latest
    #needs: tagging
    steps:
      - uses: actions/checkout@v2

      - name: Set environment for main branch
        shell: bash
        if: github.ref == 'refs/heads/main'
        run: |
          echo "BUCKET_NAME=autoscript-one-main" >> $GITHUB_ENV
          echo "PROJECT_CONF=staging" >> $GITHUB_ENV

      - name: Setup dotnet cli
        uses: actions/setup-dotnet@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Add devexpress nuget source
        run: nuget sources Add -Name "DXFeed" -Source https://nuget.devexpress.com/3CbmZLhj9ssLWS6tJMxq3FPGyDdXXgCnKRbbRpE3uKj4nGjseW/api


      - name: dotnet publish
        run: |
          dotnet publish -r win-x64 --self-contained=true --configuration staging --verbosity m TestGithubPipeline.sln  ###remove echo

      - name: Upload build
        shell: bash
        run: |
          cd TestGithubPipeline
          ls -ltr
          #aws s3 cp Releases s3://$BUCKET_NAME --recursive ###remove echo
